In [20]:
import pandas as pd
import requests

In [21]:
print(f"pandas version:  {pd.__version__}")
print(f"requests version: {requests.__version__}")

pd.Timestamp.now()
# pd.Timestamp.now().strftime('%Y-%m-%d')

pandas version:  1.5.3
requests version: 2.28.2

Timestamp('2023-03-31 17:20:37.269567')

In [22]:
from getpass import getpass
api_key = getpass()

In [23]:
api_key

'pk6dcgaCKw9Gq2k8guPKKTA0Z7tGrpfZ'

In [26]:
# Request headers
headers = {
    "api-key": api_key,
}

params = {"resource_id": "d13e3be5-9020-4a78-9a7e-760b2dcbf6be", "limit": 10}
r = requests.get(
    "https://opend.data.go.th/get-ckan/datastore_search", params, headers=headers
)
if r.ok:
    j = r.json()
    records = j["result"]["records"]

df = pd.DataFrame(records)
df

Empty DataFrame
Columns: []
Index: []

In [27]:
# r.json()
r

In [30]:
download_link = 'https://data.go.th/dataset/e81eb885-7d97-4b50-b77d-f55c74183203/resource/583e3b6a-cf9a-40ae-8746-7632985641d4/download/255802_contract.csv'

# df = pd.read_csv(download_link)

df = pd.read_csv(download_link, encoding="iso8859-11")
# df = pd.read_csv(download_link, encoding="tis-620")
# df = pd.read_csv(download_link, encoding="cp874")
# df = pd.read_csv(download_link, encoding="thai")

df

C:\Users\A715-72G\AppData\Local\Temp\ipykernel_4256\1140238787.py:5: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(download_link, encoding="iso8859-11")

,proj_no,proj_name,subdep_name,annce_date,proj_mny,cost_build,mthd_name,typ_name,win_tin,corp_name,contrct_price,contrct_num,contrct_date,contrct_fhdate,lat,long
0,56025164933,ประกวดราคาซื้อเครื่องอะไหล่สำหรับรถจักรดีเซลไฟ...,ฝ่ายการพัสดุ การรถไฟแห่งประเทศไทย,21/2/2013,4768100.0,(null),ประกวดราคา,ซื้อ,1.05499E+11,บริษัท ฮั่วฮงเส็ง จำกัด,4761500,58005,4/2/2015,5/10/2015,(null),(null)
1,56035002857,จ้างเหมาบุคคลภายนอกปฏิบัติงาน ประจำชั้นบริบาล ...,เทศบาลตำบลหนองสองห้อง,(null),60000.0,(null),ตกลงราคา,จ้างทำของ/จ้างเหมาบริการ,3.4015E+12,นางสาวสุปรียา ศรีเตชะ,7500,H 233/56,1/2/2015,28/2/2013,(null),(null)
2,56035101156,ซื้อวัสดุใช้ในการเลือกตั้ง โดยวิธีตกลงราคา,เทศบาลตำบลบ้านโพธิ์,(null),5308.0,(null),ตกลงราคา,ซื้อ,3.9005E+12,นางสาว วิไลวรรณ แก้วประเสริฐ,5308,144/2556,26/2/2015,7/3/2013,(null),(null)
3,56095079124,ซื้อเวชภัณฑ์ยา 1 รายการ CALCIUM CARBORNATE...,กลุ่มงานเภสัชกรรมและคุ้มครองผู้บริโภค,(null),9630.0,(null),ตกลงราคา,ซื้อ,1.05551E+11,บริษัท พรอสฟาร์มา จำกัด,9630,552/2558,17/2/2015,19/3/2015,(null),(null)
4,56095128075,ซื้อชุดบัณฑิตน้อย โดยวิธีตกลงราคา,โรงเรียนบ้านธารมะลิ,(null),42640.0,(null),ตกลงราคา,ซื้อ,3.9611E+12,ร้านสุวิก,42640,27/2556,28/2/2015,6/3/2013,(null),(null)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282654,58285000010,ซื้อเวชภัณฑ์ยา จำนวน ๖ รายการ โดยวิธีพิเศษ,โรงพยาบาลยุวประสาทไวทโยปถัมภ์,(null),1995550.0,1995550,พิเศษ,ซื้อ,1.05523E+11,บริษัท ดีเคเอสเอช (ประเทศไทย) จำกัด,1995550.0,106/2558,27/2/2015,30/9/2015,(null),(null)
282655,58285000011,ซื้อเวชภัณฑ์ยา จำนวน ๖ รายการ โดยวิธีพิเศษ,โรงพยาบาลศรีธัญญา,(null),8084492.0,8084492,พิเศษ,ซื้อ,1.05523E+11,บริษัท ดีเคเอสเอช (ประเทศไทย) จำกัด,8084492.0,106/2558,27/2/2015,30/9/2015,(null),(null)
282656,58285000013,ซื้อเวชภัณฑ์ยา จำนวน ๖ รายการ โดยวิธีพิเศษ,โรงพยาบาลสวนสราญรมย์,(null),1079309.0,1079309,พิเศษ,ซื้อ,1.05523E+11,บริษัท ดีเคเอสเอช (ประเทศไทย) จำกัด,1079309.0,106/2558,27/2/2015,30/9/2015,(null),(null)
282657,58285000014,ซื้อเวชภัณฑ์ยา จำนวน ๖ รายการ โดยวิธีพิเศษ,สถาบันกัลยาณ์ราชนครินทร์,(null),687475.0,687475,พิเศษ,ซื้อ,1.05523E+11,บริษัท ดีเคเอสเอช (ประเทศไทย) จำกัด,687475.0,106/2558,27/2/2015,30/9/2015,(null),(null)
282658,58285000015,ซื้อเวชภัณฑ์ยา จำนวน ๖ รายการ โดยวิธีพิเศษ,สถาบันจิตเวชศาสตร์สมเด็จเจ้าพระยา,(null),1841127.6,1841127.6,พิเศษ,ซื้อ,1.05523E+11,บริษัท ดีเคเอสเอช (ประเทศไทย) จำกัด,1841127.6,106/2558,27/2/2015,30/9/2015,(null),(null)